### PR TITLE
Update svelte.md

### PR DESCRIPTION
**Pull request by daveychu**
Change to how it's described at https://svelte-native.technology/docs#frame. The original code doesn't seem to work for me:

`NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'addEventListener' of undefined`

`Type 'typeof Home__SvelteComponent_' is not assignable to type 'string'.ts(2322)`

### CODE REVIEW

**Comment by daveychu** [comment]
@cla-bot check

**Comment by rigor789** [comment]
I don't think this is correct - you are removing the frame with this change... Running the tutorial app seems to work fine with the above: https://github.com/NativeScript/tutorials/blob/main/svelte-tutorial/app/App.svelte

image

**Comment by daveychu** [comment]
Sorry, the first commit was incomplete.

I compared my repo with the `svelte-tutorial` repo to see what could be the cause of my problem. It looks like my execution of `ns create example-app --svelte` created an `app.ts` with `svelteNativeNoFrame` rather than `svelteNative` which doesn't seem to work with the example code.

I honestly just started with SvelteNative/NativeScript so have no idea what the supposed solution is. Someone might want to take a look at this so newcomers don't get stuck like me. Unless it's an error on my part of course, then ignore this PR 😅 .

Edit: The `create` actually sets up `App.svelte` like in the new commit (except `Home.svelte` is in `components` folder).

**Comment by rigor789** [comment]
Good catch on the `svelteNativeNoFrame` vs `svelteNative` difference, I think we should update the tutorial to use the defaults from `ns create`...

**Pull request closed without merging**
