### PR TITLE
Added API description for the Payments: IAP & Subscriptions plugin

### PR DESCRIPTION
**Pull request by Ombuweb**
Added the API section describing all the methods offered by the plugin.

### CODE REVIEW

**Comment by rigor789** [comment]
Hi @Ombuweb thanks for the PR, could you open the PR against this file: https://github.com/NativeScript/payments/blob/main/packages/payments/README.md as the contents in this repo are updated daily from the plugin readmes (so your changes here would disappear in ~24hours).

Sorry for the confusion - we plan to make this better when we get the chance...

**Comment by Ombuweb** [comment]
Hi @rigor789, no problem.  I will open it against the other file.

**Comment by Ombuweb** [comment]
One question @rigor789, does that mean I should use the packages' README.md when contributing to packages docs and docs-new for other contributions?

**Comment by rigor789** [comment]
Yep, plugins are separate and just pulled in daily on CI

The rest is managed here

**Pull request closed without merging**
