### PR TITLE
fix: template is capitalized in the import, should be when used also

### PR DESCRIPTION
**Pull request by winescout**
Just working through the Svelte tutorial and found this small typo

### CODE REVIEW

**Comment by winescout** [comment]
@cla-bot check

**Comment by rigor789** [comment]
@halfnelson hey, can you give this a quick review?

**Comment by winescout** [comment]
Thanks for looking at this.  I just ran into the same thing a bit further down the page.  I'll update this PR:  
https://github.com/NativeScript/docs-new/blob/develop/tutorial/svelte.md?plain=1#L419

**Comment by winescout** [comment]
@cla-bot check

**Comment by halfnelson** [comment]
Yep, Template needs to be capitalized because it is a svelte component (not a nativescript element). Thanks for this.

**Review by rigor789 — APPROVED** [review]

**Pull request merged**
